baseURL = 'https://evsky.art/'
languageCode = 'en-us'
title = "OKNOTOK"
theme = 'holy'
copyright = "© 2023 OKNOTOK"
staticDir = ['static']

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

